### ISSUE TITLE
Example of how to use this polyfill

### ISSUE THREAD

**Issue by ericchenshine** [jonathantneal/element-qsa-scope#2]
Hi Jonathantneal, 

Thanks for your module. We want to use it in our project. Just wondering if you could provide a little bit more to demonstrate how to use this library in the ES6 + Webpack scenario. 

Cheers

**Comment by jonathantneal** [comment]
Not a problem.

From your terminal, install `element-qsa-scope`:

```bash
npm install element-qsa-scope
```

Then import the module in your main JS file:

```js
import 'element-qsa-scope'
```

**Comment by ericchenshine** [comment]
Hi Jonathantneal,
That's great.
Thanks a lot!
